### ISSUE TITLE
tabs with display flex

### ISSUE THREAD

**Issue by milahu** [atk/solid-blocks#12]
tabs are not working with flex layout
the `hidden="hidden"` attribute has no effect

fixed in https://github.com/milahu/solidjs-blocks-vanillajs/commit/1812796e7e5020e59a496c126406de1e4fc04b12
maybe there is a better solution than `display:none`

```jsx
// src/App.jsx

import styles from './App.module.css';

export default function App(props) {
  return (
    <div class={styles.App}>

      <Tabs classList={{ [styles.flexcolumn]: true }}>

        <Tab>a</Tab>
        <TabContainer classList={{ [styles.flexcolumn]: true }}>
          {"a ".repeat(1000)}
        </TabContainer>

        <Tab>b</Tab>
        <TabContainer classList={{ [styles.flexcolumn]: true }}>
          {"b ".repeat(1000)}
        </TabContainer>

      </Tabs>
    </div>
  );
}
```

```css
/* src/App.module.css */

.App {
  height: 100vh;
  display: flex;
  flex-direction: column;
  /*align-content:stretch;*/
}

.flexcolumn {
  display: flex;
  flex-direction: column;
  flex-grow: 1;
}
```
